### ISSUE TITLE
cannot boot from activated BE (zedenv, EFI+systemd-boot)

### ISSUE THREAD

**Issue by TPKato** [danboid/ALEZ#11]
Even if I make new BE and activate it using zedenv, 

    zedenv create newbe
    zedenv activate newbe
    reboot

still `default` will be used to boot, although I expected that `newbe` would be used.
The reason is that `options zfs=${zroot}/ROOT/default` is specified in `efi/loader/entries/zedenv-default.conf` (created by ALEZ).
But this should be `zfs=bootfs` to work BE-activation correctly. 
I think this occurs with GRUB, too, but I've not tested.

    --- alez.sh,orig	2018-10-29 12:38:18.000000000 +0100
    +++ alez.sh	2018-10-28 22:38:06.000000000 +0100
    @@ -200,7 +200,7 @@
             title           [default] (Arch Linux)
             linux           /env/zedenv-default/vmlinuz-${2}
             initrd          /env/zedenv-default/initramfs-${2}.img
    -        options         zfs=${zroot}/ROOT/default rw
    +        options         zfs=bootfs rw
     EOF
     }

**Comment by danboid** [comment]
@johnramsden would be better comment on this as I've not tested EFI support yet

**Comment by johnramsden** [comment]
Assuming your config is correct, this isn't ALEZ related. It should be correct assuming the variables aren't present in your config, `zfs=bootfs` is not needed. If you still think your config is wrong, please post `/mnt/efi/loader/entries/zedenv-default.conf`

Regarding zedenv, you need to enable the `systemdboot` [plugin](https://zedenv.readthedocs.io/en/latest/plugins.html) or use the `-b systemdboot` option during activation. 

To enable the systemdboot plugin:

```
zedenv set org.zedenv:bootloader=systemdboot
```

Try enabling the plugin and re-activating. If you still have issues with zedenv you're welcome to open an issue on the [zedenv repo](https://github.com/johnramsden/zedenv/issues/new).

**Comment by TPKato** [comment]
Thank you for your reply.

I understood that it was my mistake.
As you guessed, I have used zedenv without plugins.

So this issue should be closed.
