### ISSUE TITLE
dialog prompt is unclear regarding "-part"

### ISSUE THREAD

**Issue by a-schaefers** [danboid/ALEZ#12]
I tried first in ansi-term and then xterm, ssh'd into a virtualbox guest.

The dialog screens were not clear at one point, see screenshot attached.

Basically, it told me to choose partitions with -part, but the dialog
cut-off made it impossible for me to tell which entry I should choose,
because while I was cycling through the list, they all had cutoff the
string before the *-part section.

At this point I C-c and ls -al /dev/disk/by-id and saw there were two
partitions with -part, which then makes question which one I was
supposed to pick anyways?

Thank you

![2018-11-01-125846_1366x768_scrot](https://user-images.githubusercontent.com/26800291/47888957-8953b500-de04-11e8-911d-ee692e828770.png)

edit: So you can see in this screenshot, the disk string in the dialog is cutoff, not being wide enough. I cannot see to the right the remaining *-part. Clearly then I break with C-c and took a look at the disks with ls -al /dev/disk... (That's why you only see the top-half fragment of the dialog.)

**Comment by johnramsden** [comment]
I'm pretty sure setting the `HEIGHT` and `WIDTH` variables at the [top of the script](https://github.com/danboid/ALEZ/blob/8e23c750a9e464439d37231b3a6299a417111738/alez.sh#L22) to `0` should fix this. 
 Do you mind trying again with them set to `0`, and let us know if it fixes the problem for you?

**Comment by a-schaefers** [comment]
Yeah @johnramsden , that fixed it.
