### ISSUE TITLE
ZFS hook failed to be added for LTS and feedback

### ISSUE THREAD

**Issue by dmp1ce** [danboid/ALEZ#16]
I'm trying out ALEZ on a new laptop. I have yet to successfully install Arch with ZFS root using ALEZ. I just tried systemd-boot and LTS but when rebooting the file system failed to mount. I thought I saw some error messages about zfs hook when the installer was running but it went by very fast. Is there a log?

I am trying again with the Stable option and grub2 but it taking a long time to install. I feel like maybe my mirror is not optimized for me. Should I prepare the mirrorlist before running `alez`.

This will be amazing if the installer works because I was getting overwhelmed trying to manually install root ZFS. I was able to get through the Ubuntu root ZFS install using a very specific guide online.

My second install just finished and I did notice that the zfs hook failed to install. Should I try to manually install it before rebooting? What do you recommend?

**Comment by dmp1ce** [comment]
I tried to install `zfs-linux` manually but it looks like `zfs-linux` needs an update for the new kernel so I guess I need to wait a day for the install to work.

**Comment by danboid** [comment]
Hi David

Due to the frequency at which the kernels get updated in Arch and the zfs modules relying on an unofficial repo, the repos do unfortunately quite frequently fall out of sync and break ALEZ. Try again tomorrow and you may have more luck.

**Comment by dmp1ce** [comment]
I was able to install last night. Thank you very much!

**Comment by dmp1ce** [comment]
Perhaps the script can check `zfs-linux` to see if dependencies are available before installing so that the user can be warned about the script failing.
