### ISSUE TITLE
silent failure on blocked hkp server

### ISSUE THREAD

**Issue by sdirkwinkel** [danboid/ALEZ#27]
I've had ALEZ silently fail by not installing any zfs packages because the hkp keyserver was not reachable. ALEZ completes seemingly successfully but the kernel can't mount the root partition on the next boot.
Changing `--keyserver hkp://pool.sks-keyservers.net` to `--keyserver hkp://pool.sks-keyservers.net:80` fixed it because some corporate firewall blocks the default keyserver port.

Maybe ALEZ should at least fail outright if keyservers can't be reached

**Comment by danboid** [comment]
I have added the port to the hkp addresses.

You are right in saying the installer should throw an error if fetching the repo key fails so I will add that in later.
