### ISSUE TITLE
zedenv for Boot Environments in ALEZ (and how to do networking)

### ISSUE THREAD

**Issue by Kodiman** [danboid/ALEZ#34]
Hi, Dan, Your ALEZ is excellent!
Fresh install today with newest version of iso.
Want to install and configure zedenv or beadm.
pacman -Syu results in this error.
Protocol "rsync" not supported or disabled in libcurl
How to fix that? Please do fix this. Thanks.

**Comment by johnramsden** [comment]
You might need to update your mirrorlist, it's unlikely this is a ALEZ related issue. Are you getting a message like:

```
error: failed retrieving file '<PACKAGE>-x86_64.pkg.tar.xz' from <MIRROR> : Protocol rsync not supported or disabled in libcurl
```

First i'd try just running `pacman -Syyu`, and seeing if that fixes the issue. If it doesn't, maybe update your mirrorlist.

**Comment by Kodiman** [comment]
hi, yes that is the error. also, says "could not resolve host". pacman -Syyu fails with same error. ping fails with both IP or hostname. this ALEZ arch linux is installed in linux qemu/kvm VM with default settings. the fresh install of ALEZ fails to network. should it network by default? how to configure networking in ALEZ? thanks

**Comment by johnramsden** [comment]
Yes you need to set up a networking. It's essentially a system with nothing configured, all that's been done is ZFS has been configured.

I'd recommend going through [Network configuration](https://wiki.archlinux.org/index.php/Network_configuration), and taking a look through the [Installation guide](https://wiki.archlinux.org/index.php/Installation_guide) in case there was anything else you wanted to set up.

The easiest way to set up networking on a wired host would be using [`systemd-networkd`](https://wiki.archlinux.org/index.php/Systemd-networkd), and optionally [`systemd-resolved`](https://wiki.archlinux.org/index.php/Systemd-resolved)

Create `/etc/systemd/network/20-wired.network`

Assuming your network adapter is `en*`, the following configuration should work:

```
[Match]
Name=en*

[Network]
DHCP=yes
```

Then start and enable `systemd-networkd.service`, and optionally `systemd-resolved.service`:

```
systemctl enable --now systemd-networkd.service systemd-resolved.service
```

**Comment by Kodiman** [comment]
Hi, John, You solved it. The network works, so pacman works. No errors. Next goal is to make boot environments.

beadm seems to be unavailable in arch linux? So trying zedenv?

pacman -S zedenv
results in "error: target not found: zedenv"

How to install and configure zedenv to make boot environments?

Much appreciated. Thanks!

**Comment by johnramsden** [comment]
You need to install [`zedenv`](https://github.com/johnramsden/zedenv) and [`zedenv-grub`](https://github.com/johnramsden/zedenv-grub) from the [AUR](https://wiki.archlinux.org/index.php/Arch_User_Repository#Installing_packages) or source.

[As the Wiki](https://wiki.archlinux.org/index.php/AUR_helpers) mentions you should probably familiarize yourself with `makepkg`, but if you want the easy way out, install an AUR helper, I'd recommend `yay` as a good one to start with.

This should get you started:

```
pacman -S base-devel git
```

Switch to your user and install `yay`

```
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -sic
```

Now you can install `zedenv` and if you're using GRUB, `zedenv-grub`.

```
yay -S zedenv zedenv-grub
```

If using `zedenv-grub` (as root):
```
zedenv set org.zedenv.grub:bootonzfs=yes
```

You'll now want to read the documentation for `zedenv`.

---

This is a little bit out of scope of ALEZ, so i'm going to close this. If you end up running into a bug with `zedenv` feel free to open an issue there.

You should probably read through the installation guide, is it a good place to start. You want to familiarize yourself with the wiki, as it has most of the answers you will need.

**Comment by Kodiman** [comment]
Hi, John, Thanks for those details. The zedenv and zedenv-grub are now installed and work. You are the best. Thanks!
