### ISSUE TITLE
UEFI systemd-boot install fails after selecting ESP partition

### ISSUE THREAD

**Issue by erosegren** [danboid/ALEZ#37]
ISO used:  archlinux-alez-2019.05.26.16.11.18-x86_64.iso  booted in UEFI mode.

Just tried to install a zfs mirror install on two brand new 1 tb SSDs. Both drives were partitioned using the auto partitioning in the script. It successfully created the zfs mirror, then asks me to choose the partition to install the ESP to.  As soon as I select /dev/sda1 the installer fails with this error.

![IMG_20190612_064453263](https://user-images.githubusercontent.com/9153599/59393630-60a47e00-8d4a-11e9-9603-eb185fcda148.jpg)

Am I doing something wrong here?
I chose the systemd-boot option for the boot loader.
For the zfs mirror I chose /dev/sda2 and /dev/sdb2.
There are no other drives connected to the system except the usb flash drive.

**Comment by johnramsden** [comment]
Was the ESP partitioned with the script? The error makes me think maybe it's not a valid ESP.

Can you run:

```
blkid /dev/sda1 && fdisk -l /dev/sda
```

**Comment by erosegren** [comment]
Output from running: blkid

```
/dev/sdb2: LABEL="zroot" UUID="16368558207180991846" UUID_SUB="16334776569763590417" TYPE="zfs_member" PARTUUID="ff8cd49e-a03c-4f0e-a032-1b59394f61af"
/dev/sdc1: UUID="2019-05-26-16-24-18-00" LABEL="ARCH_201905" TYPE="iso9660" PTUUID="7821e2d2" PTTYPE="dos" PARTUUID="7821e2d2-01"
/dev/sdc2: SEC_TYPE="msdos" LABEL_FATBOOT="ARCHISO_EFI" LABEL="ARCHISO_EFI" UUID="C5B0-B099" TYPE="vfat" PARTUUID="7821e2d2-02"
/dev/loop0: TYPE="squashfs"
/dev/sda2: LABEL="zroot" UUID="16368558207180991846" UUID_SUB="13240638619056703811" TYPE="zfs_member" PARTUUID="5b0cc410-1d07-473c-a7bd-88e19c0b56b1"
/dev/sdb1: PARTUUID="210229cb-b9af-4892-b91f-07eeba7cf114"
```

Output from running: fdisk -l /dev/sda

```
Disk /dev/sda: 931.5 GiB, 1000204886016 bytes, 1953525168 sectors
Disk model: CT1000MX500SSD1 
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes
Disklabel type: gpt
Disk identifier: AB550D16-9544-40A3-B49A-3C7DBFF601CF

Device       Start        End    Sectors   Size Type
/dev/sda1     2048    4196351    4194304     2G EFI System
/dev/sda2  4196352 1953525134 1949328783 929.5G Solaris root
```


Output from running: fdisk -l /dev/sda1
```

Disk /dev/sda1: 2 GiB, 2147483648 bytes, 4194304 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes
Disklabel type: dos
Disk identifier: 0x00000000
```

Yes both drive partition layouts were created with the script. Looks like /dev/sda1 does not show up at all when running blkid.

Additional screenshots..

Just before selecting the esp partiton:

![IMG_20190613_064454500](https://user-images.githubusercontent.com/9153599/59428325-e6f0ac80-8daa-11e9-8b2d-e7ea9e128859.jpg)

Odd that is tells you to select the 2nd partition and not the 1st.


Just after selecting /dev/sda1 as esp partition:

![IMG_20190613_064632340](https://user-images.githubusercontent.com/9153599/59428444-3fc04500-8dab-11e9-9f56-176f149e349c.jpg)

**Comment by johnramsden** [comment]
So I just ran through a mirrored install with systemd-boot and couldn't replicate the issue. Maybe there's something left over from a old file system that's confusing things, could you select the wipe option during partitioning and try again?

If that doesn't help, it might be useful to see if you can install in a non mirrored setup.

**Comment by danboid** [comment]
It should be mentioned, if @etr06 isn't already aware, that BIOS installation is recommended for RAID installations if your hardware supports it because the UEFI partition doesn't get installed to both disks, hence if you EFI disk fails, it won't boot.

The only other Linux distro I'm aware of with proper ZFS support in its installer is proxmox and they have opted not to support UEFI because of this shortcoming. It is sad that those behind UEFI didn't give any thought toward redundancy.

Maybe we should make RAID 1 installation BIOS only too?

**Comment by erosegren** [comment]
I will try the install again with mirrored and non-mirrored. In previous attempts I wiped the drives with each new install. Its possible i am just doing something wrong here..

After I get back from work I will update this. Thanks for your help.

**Comment by erosegren** [comment]
Well sorry looks like it was a bad SSD. When I selected /dev/sdb as the ESP partition the installer completed without issue. Seems like /dev/sda is a bad drive. Sorry to waste your time on this one...

@danboid  You make a good point about BIOS boot for RAID installations, I will probably reinstall again now that I know that. 
Thanks again.

**Comment by johnramsden** [comment]
I don't know about UEFI being a _bad_ choice, there are ways to mirror your UEFI partition and/or provide some sort of backup by having multiple UEFI partitions. Personally I would never consider using BIOS nowadays, largely due to BIOS's complexity, no support for disks over to terabytes, and how much I dislike GRUB. I guess it comes down to how much of a problem you think it's going to be if your boot partition dies. If it happened to me I would plug in a USB drive, chroot in, recreate it and be back up and running in half an hour.

**Comment by Titaniumtown** [comment]
Same issue, the ssd is fine. I'm trying to do grub

**Comment by Titaniumtown** [comment]
wait nvm
