### ISSUE TITLE
Network is unreachable after installation

### ISSUE THREAD

**Issue by globalviking** [danboid/ALEZ#51]
Hello,

First of all, a big thanks to everyone involved in this project. This will make my life so much easier.

I am having an issue.

I booted up the iso. Needed internet to install so I hooked up my Android and enabled tethering. I ran a ping and it “just worked”. So I ran 'alez' and followed the prompts until I got:
`Installation complete. You may now reboot into your new install.`
Before rebooting I mounted the datasets and partitions, entered chroot, ran passwd, set hosts file, set hostname, set time zone, enabled UTF-8, ran locale-gen, exited chroot unmounted and exported. After rebooting I connected my Android, enabled tethering, ran ping and got:
`ping: connect: Network is unreachable`

Did I miss something? Any help would be greatly appreciated.

**Comment by johnramsden** [comment]
You need to [configure your network](https://wiki.archlinux.org/index.php/Network_configuration) . ALEZ basically gives you a bootable Arch ZFS system and that's about it. It doesn't make many assumptions about your configuration.

**Comment by globalviking** [comment]
I got it working. Thanks. I installed dhcpcd.
