### ISSUE TITLE
archzfs.com certificate not valid yet

### ISSUE THREAD

**Issue by ec1oud** [danboid/ALEZ#52]
It may be that archzfs.com has a bad SSL installation somehow.

The result is that zfs-utils and zfs-modules are not getting installed automatically, and I can't install them manually until I change the server to use http instead of https, in /etc/pacman.conf.

The error was something like "certificate not valid yet".

**Comment by johnramsden** [comment]
Interesting, I wonder if maybe the time is set wrong on your computer leading it to think it's in the past where the certificate would not be valid.

The certificate for the [repo](https://archzfs.com/archzfs/x86_64/) currently shows:

```
Issued On	Tuesday, October 15, 2019 at 6:14:42 PM
Expires On	Monday, January 13, 2020 at 5:14:42 PM
```

If the same error occurs for you again I would check the date and make sure it is correct. I'm not able to reproduce this.

**Comment by ec1oud** [comment]
yes nevermind... the clock was wrong; sorry for the noise.
