### ISSUE TITLE
grub-mkconfig question

### ISSUE THREAD

**Issue by ghost** [danboid/ALEZ#54]
Sorry to bother you with this, but my google foo is failing me.

I just installed amd-ucode and wanted to update my grub.cfg and ran `grub-mkconfig -o /boot/grub/grub.cfg` and I get the following error.

```
/usr/bin/grub-probe: error: failed to get canonical path of `/dev/ata-KINGSTON_SA400S37480G_50026B7782EE112D-part2'.
```

What am I doing wrong? Thanks.

**Comment by johnramsden** [comment]
You need to set `ZPOOL_VDEV_NAME_PATH=1` as an environment variable.

```
ZPOOL_VDEV_NAME_PATH=1 grub-mkconfig -o /boot/grub/grub.cfg
```

**Comment by ghost** [comment]
Thank you!
