### ISSUE TITLE
ALEZ works great

### ISSUE THREAD

**Issue by lukebakken** [danboid/ALEZ#55]
@danboid @johnramsden thank you for this project. I recently returned to Arch Linux for daily development of RabbitMQ and ALEZ made installation on ZFS just as easy as my FreeBSD machine.

:partying_face: 

I hope you don't mind the superfluous GitHub issue.

**Comment by lukebakken** [comment]
PS I first heard about ALEZ [here](https://www.phoronix.com/forums/forum/software/general-linux-open-source/1085709-new-and-improved-alez-the-arch-linux-easy-zfs-installer)

**Comment by johnramsden** [comment]
Thank you for the nice feedback. :relaxed:

**Comment by danboid** [comment]
Thanks Luke!

Your positive feedback and appreciation is much appreciated!
