### ISSUE TITLE
ArchZFS repo broken

### ISSUE THREAD

**Issue by ghost** [danboid/ALEZ#61]
ALEZ is currently unable to access the archzfs repository.

A workaround is to use the archiso-zfs package at https://github.com/eoli3n/archiso-zfs 

Instead of 'pacman -Syy" to refresh repos run 'curl -s https://eoli3n.github.io/archzfs/init | bash'

From there you can run alez as usual. 

Should we consider adding this command to the alez script when building an ALEZ image?

**Comment by johnramsden** [comment]
Thanks, as soon as the kernel is in line with archzfs I will create a new image with this fixed.

**Comment by johnramsden** [comment]
Released [archlinux-alez-2020.07.28.04.34.53](https://github.com/danboid/ALEZ/releases/tag/archlinux-alez-2020.07.28.04.34.53) which fixes this issue.

It shouldn't be an issue in the future, their key had just expired.
