### ISSUE TITLE
unexpected behavior from useradd while chrooted

### ISSUE THREAD

**Issue by ghost** [danboid/ALEZ#62]
I tried adding my user account while chrooted with "useradd -m -g users -G wheel -s /bin/bash lenny" as I have dome for some time. I could see my home directory at /home/lenny and the permissions looked good. However when I rebooted and tried to log in I got an error stating that I had no home directory. When I looked /home/lenny was no longer visible. I tried adding my user account by running "useradd -d /home/lenny -g users -G wheel -s /bin/bash lenny" instead but that did not work either. I was able to confirm this by doing a couple of passes on my test system. For what its worth I launched ALEZ with "alez 2> ~/error.log" to see if it would capture anything. What I got was:

>error: '/linux-5.7.12.arch1-1-x86_64.pkg.tar.xz': could not find or read package
>Created symlink /etc/systemd/system/multi-user.target.wants/zfs.target -> /usr/lib/systemd/system/zfs.target.

**Comment by johnramsden** [comment]
Did you happen to mount the home dataset? I imagine that would be the problem.

```
mount -t zfs "zroot/data/home" "${installdir}/home"
```

**Comment by ghost** [comment]
I ran a "zfs list" and saw zroot/data/home listed so I though that the dataset was in fact mounted. Maybe that was the wrong approach. What would you suggest?

**Comment by johnramsden** [comment]
To see mounted:

```
zfs mount
```

**Comment by joatmor** [comment]
Hi John,

Thank you for steering me in the right direction. I was looking for a complex problem and it wasn't even a problem. I am currently trying to get better with zfs. Thanks to ALEZ I have now have the best Linux box I have ever seen.
How are things in Canada? My home state of New Hampshire is open but with restrictions and mandatory face masks. The job market has been completely devastated. Fortunately for me I attended orientation today for a new job that starts next week. Thank you again and keep safe.
Len Huppe

**Comment by ghost** [comment]
I did a "mount -t zfs zroot/data/home /mnt/home" before chrooting and that fixed it.
