### ISSUE TITLE
Switch to semantic versioning?

### ISSUE THREAD

**Issue by johnramsden** [danboid/ALEZ#9]
Right now the versioning scheme being used means every update has another major version. The recommended standard versioning scheme is [semantic versioning](https://semver.org/) using MAJOR.MINOR.PATCH. This would allow a minor version to exist and if bugs are noticed, a patch version could come out. Would you consider using semantic versioning?

**Comment by danboid** [comment]
Makes sense I suppose. I do enjoy freeform versioning tho, it has to be said.

**Comment by johnramsden** [comment]
Keep on using it then, was just a thought.
